### ISSUE TITLE
Scipts to create meta files?

### ISSUE THREAD

**Issue by ArturoDeza** [edenton/drnet#7]
Hey Emily,

Looking into using your model for another dataset. What do the files in the meta folder contain? They seem like bounding box coordinates probably to be used for the Pose Encoder. Is this correct?  Could you share the code to creating these meta files?

[EDIT]: Meta files seem to contain the initial and final flags of a cycle (in frame time steps) regarding the activity of the person. This is later used in the :getSequence() method in the kth.lua file.

Thanks,
Arturo

**Comment by noootown** [comment]
Same question, seems that the kth meta file is missing on your server.
Thanks,
Hung I Chiu

**Comment by javierselva** [comment]
Yes! Same here, after downloading and converting the KTH dataset I get the following:
> <torch> set nb of threads to 1	
<gpu> using device 0	
Initialized models from scratch
/root/torch/install/bin/luajit: /root/torch/install/share/lua/5.1/trepl/init.lua:389: /root/torch/install/share/lua/5.1/threads/threads.lua:183: [thread 1 callback] **cannot open </datasets/kth/processed/meta/train_meta.t7>** in mode r  at /tmp/luarocks_torch-scm-1-7664/torch7/lib/TH/THDiskFile.c:673
stack traceback:
	[C]: at 0x7f0b876db720
	[C]: in function 'DiskFile'
	/root/torch/install/share/lua/5.1/torch/File.lua:405: in function 'load'
	./data/kth.lua:19: in function '__init'
	/root/torch/install/share/lua/5.1/torch/init.lua:91: in function </root/torch/install/share/lua/5.1/torch/init.lua:87>
	[C]: in function 'KTHLoader'
	./data/kth.lua:114: in main chunk
	[C]: in function 'require'
	./data/data.lua:10: in function 'getDatasourceFun'
	./data/threads.lua:28: in function <./data/threads.lua:18>
	[C]: in function 'xpcall'
	/root/torch/install/share/lua/5.1/threads/threads.lua:234: in function 'callback'
	/root/torch/install/share/lua/5.1/threads/queue.lua:65: in function </root/torch/install/share/lua/5.1/threads/queue.lua:41>
	[C]: in function 'pcall'
	/root/torch/install/share/lua/5.1/threads/queue.lua:40: in function 'dojob'
	[string "  local Queue = require 'threads.queue'..."]:13: in main chunk
stack traceback:
	[C]: in function 'error'
	/root/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
	train_drnet_skip.lua:332: in main chunk
	[C]: in function 'dofile'
	/root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00406670

Also, as @ArturoDeza I'd like to use the model with other datasets. It'd be great if you could share the code to create this meta files.

Thanks in advance,
Javier.

**Comment by edenton** [comment]
Hey sorry for the delay here. I've added the meta files again, same location. Also, instructions for how to download and process the KTH dataset can be found here: https://github.com/edenton/drnet  .. I'll eventually get around to adding all these instructions to the python version .. 

The meta data files don't contain any bounding box information. They simply contain a list of videos to be used for training and testing, and for each video, the start and frames for different clips. Basically KTH provides long videos for each person/clothing/action combination. These video clips contain sequences of the person, for example, walking across the frame. But they also contain long segments where the person is out of view of the camera. In order to avoid training the model on a sequence of 20 frames with no one in the camera view, I chop the video up into 3-4 (typically 4, but if I recall correctly, there was at least one video with less than 4) short segments. Anyways, the meta files contain all this info. 

Again, sorry for the delay!
